const eventList = [
  {
    id: 1,
    title: "PES 2021 avec Wejdene",
    theme: "Gaming",
    date: "11/12/20",
    hour: "15h30",
    author: "Robin",
    description: "PES 2021 tournaments",
    infos: "Google meet lien : lalalalala",
    image: "https://images.rtl.fr/~r/880v587/rtl/www/1205715-wejdene-est-l-une-des-artistes-francaises-les-plus-vogues-de-l-ete-2020.jpg",
  },
  {
    id: 2,
    title: "Cooking class avec Wejdene",
    theme: "Cooking",
    date: "10/12/20",
    hour: "19h",
    author: "Maxime",
    description: "make Welsh ",
    infos: "Chez moi 2 rue de la Hess 75018",
    image: "https://i.ytimg.com/vi/M2l-X9M6zAo/maxresdefault.jpg",
  },
  {
    id: 3,
    title: "Concert de Wejdene",
    theme: "Music",
    date: "09/11/20",
    hour: "10h15",
    author: "Vincent",
    description: "Introduction of Go",
    info: "youhou youhou youhou",
    image: "https://images.bfmtv.com/UF35vpc35uTxdV5rUSEhlZk8aOQ=/115x4:1251x643/1136x0/images/Wejdene-dans-le-clip-de-Reflechir-972414.jpg",
  },
  {
    id: 4,
    title: "L'islamo-gauchisme avec Wejdene",
    theme: "Politics",
    date: "27/11/20",
    hour: "17h00",
    author: "David",
    description: "lorem ipsum *30",
    infos: "discord serveur Naniarritz",
    image: "https://cdn-www.konbini.com/fr/images/files/2020/07/wejdene.jpg"
  },
  {
    id: 5,
    title: "Comment voler la coupe d'europe avec CR7",
    theme: "Sport",
    date: "30/11/20",
    hour: "18h00",
    author: "Justine",
    description: "potion",
    info: " loloS",
    image: "https://static.onzemondial.com/photo_article/455248/186855/1200-L-juventus-cristiano-ronaldo-dpasse-deux-lgendes-avec-un-record.jpg",
  },
];

export default eventList;
